In [28]:
import vector
import numpy as np

In [9]:
def pt(p):
    z = np.array([0,0,1])
    return np.linalg.norm(p-np.dot(p,z)*p)

def phi(p):
    return np.arctan(p[1]/p[0])

def theta(p):
    return np.arctan(p[2]/pt(p))

def eta(p):
    return -np.log(np.tan(theta(p)/2))

In [31]:
def four_momentum(vector):
    p = np.zeros((4,))
    p[0] = vector.E
    p[1] = vector.pt*np.cos(vector.phi)
    p[2] = vector.pt*np.sin(vector.phi)
    p[3] = vector.pt*np.sinh(vector.eta)

    return p

In [32]:
def mass(p):
    return np.sqrt(p[0]**2-(p[1]**2+p[2]**2+p[3]**2))

In [36]:
p = vector.array({"pt" : [2,3],
                          "phi" : [np.pi/2,0.2],
                          "eta" : [0,5],
                          "M" : [10,6]})
p1 = p[0]
p2 = p[1]
ptot = p[0]
ptot += p2

In [43]:
p1_4 = four_momentum(p1)
p2_4 = four_momentum(p2)
print(p1_4, mass(p1_4))
print(p2_4, mass(p2_4))

[1.0198039e+01 1.2246468e-16 2.0000000e+00 0.0000000e+00] 10.0
[222.71068259   2.94019973   0.59600799 222.60963173] 6.000000000001819


In [42]:
ptot_4 = p1_4 + p2_4
print(ptot_4[1:])
print("pt : ", pt(ptot_4[1:]))
print("phi : ", phi(ptot_4[1:]))
print("eta : ", eta(ptot_4[1:]))
print("Mass : ", mass(ptot_4))

[  2.94019973   2.59600799 222.60963173]
pt :  49340.095376673904
phi :  0.7233070492481141
eta :  6.094224885451682
Mass :  68.38157963745243


In [ ]:
print(ptot)

In [17]:
dictionary = {'tmm' : 0, 'tee' : 1, 'ttm' : 2}
dictionary['tte'] = len(dictionary)
print(dictionary)
dictionary['bonsoir'] = len(dictionary)
print(dictionary)
print(list(dictionary.keys()))
print(list(dictionary.values()))

{'tmm': 0, 'tee': 1, 'ttm': 2, 'tte': 3}
{'tmm': 0, 'tee': 1, 'ttm': 2, 'tte': 3, 'bonsoir': 4}
['tmm', 'tee', 'ttm', 'tte', 'bonsoir']
[0, 1, 2, 3, 4]
